#
#   TINET (TCP/IP Protocol Stack)
#  
#   Copyright (C) 2001-2009 by Dep. of Computer Science and Engineering
#                    Tomakomai National College of Technology, JAPAN
# 
#   上記著作権者は，以下の (1)〜(4) の条件か，Free Software Foundation 
#   によって公表されている GNU General Public License の Version 2 に記
#   述されている条件を満たす場合に限り，本ソフトウェア（本ソフトウェア
#   を改変したものを含む．以下同じ）を使用・複製・改変・再配布（以下，
#   利用と呼ぶ）することを無償で許諾する．
#   (1) 本ソフトウェアをソースコードの形で利用する場合には，上記の著作
#       権表示，この利用条件および下記の無保証規定が，そのままの形でソー
#       スコード中に含まれていること．
#   (2) 本ソフトウェアを，ライブラリ形式など，他のソフトウェア開発に使
#       用できる形で再配布する場合には，再配布に伴うドキュメント（利用
#       者マニュアルなど）に，上記の著作権表示，この利用条件および下記
#       の無保証規定を掲載すること．
#   (3) 本ソフトウェアを，機器に組み込むなど，他のソフトウェア開発に使
#       用できない形で再配布する場合には，次の条件を満たすこと．
#     (a) 再配布に伴うドキュメント（利用者マニュアルなど）に，上記の著
#         作権表示，この利用条件および下記の無保証規定を掲載すること．
#   (4) 本ソフトウェアの利用により直接的または間接的に生じるいかなる損
#       害からも，上記著作権者およびTOPPERSプロジェクトを免責すること．
# 
#   本ソフトウェアは，無保証で提供されているものである．上記著作権者お
#   よびTOPPERSプロジェクトは，本ソフトウェアに関して，その適用可能性も
#   含めて，いかなる保証も行わない．また，本ソフトウェアの利用により直
#   接的または間接的に生じたいかなる損害に関しても，その責任を負わない．
#  
#   @(#) $Id: Makefile.config,v 1.5 2009/12/24 05:38:58 abe Exp abe $
#

#
#  「ソースファイルのディレクトリの定義」の後に追加する。
#

#
#  TINET ソースファイルのディレクトリの定義
#
TINET_ROOT = $(SRCDIR)/tinet

#
#  TINET 1.1 との互換性のための定義
#
ifndef SUPPORT_INET4
	ifndef SUPPORT_INET6
		SUPPORT_INET4 = true
	endif
endif

#
#  ネットワークサービスに関する定義
#
TINET_DIR = $(TINET_ROOT)/net:$(TINET_ROOT)/netinet

TINET_COBJS := $(TINET_COBJS) \
	       net_buf.o net_count.o net_subr.o net_timer.o \
               in_subr.o tinet_cfg.o route_cfg.o

ifeq ($(SUPPORT_INET4),true)

	TINET_COBJS := $(TINET_COBJS) \
	               ip_input.o ip_output.o ip_icmp.o
	TINET_CDEFS := $(TINET_CDEFS) -DSUPPORT_INET4

endif

ifeq ($(SUPPORT_INET6),true)

	TINET_DIR := $(TINET_DIR):$(TINET_ROOT)/netinet6
	TINET_COBJS := $(TINET_COBJS) \
	               in6.o in6_ifattach.o nd6_rtr.o \
	               in6_subr.o ip6_input.o icmp6.o \
	               dest6.o route6.o frag6.o \
	               ah_input.o esp_input.o \
	               nd6.o nd6_nbr.o ip6_output.o
	TINET_CDEFS := $(TINET_CDEFS) -DSUPPORT_INET6

endif

ifeq ($(NET_IF),loop)

	TINET_COBJS := $(TINET_COBJS) if_loop.o
	TINET_CDEFS := $(TINET_CDEFS) -DSUPPORT_LOOP

endif

ifeq ($(NET_IF),ppp)

	TINET_COBJS := $(TINET_COBJS) \
	               ppp.o ppp_hdlc.o ppp_lcp.o ppp_fsm.o \
	               ppp_auth.o ppp_ipcp.o ppp_upap.o
	TINET_CDEFS := $(TINET_CDEFS) -DSUPPORT_PPP

ifeq ($(PPP_CFG_MODEM),true)

	TINET_COBJS := $(TINET_COBJS) ppp_modem.o 
	TINET_CDEFS := $(TINET_CDEFS) -DPPP_CFG_MODEM

endif

endif

ifeq ($(NET_IF),ether)

	#  ターゲット依存の定義のインクルード

	ifdef TOOL
	    ifdef SYS
	        -include $(SRCDIR)/config/$(CPU)-$(TOOL)/$(SYS)/Makefile.tinet
	    endif
	else
	    ifdef SYS
	        -include $(SRCDIR)/config/$(CPU)/$(SYS)/Makefile.tinet
	    endif
	endif

	TINET_COBJS := $(TINET_COBJS) if.o ethernet.o
	TINET_CDEFS := $(TINET_CDEFS) -DSUPPORT_ETHER

	ifeq ($(SUPPORT_INET4),true)

		TINET_COBJS := $(TINET_COBJS) if_ether.o

	endif

	ifeq ($(SUPPORT_INET6),true)

		TINET_COBJS := $(TINET_COBJS) if6_ether.o 

	endif

	include $(TINET_ROOT)/netdev/$(NET_DEV)/Makefile.tinet

endif

ifeq ($(SUPPORT_TCP),true)

	TINET_COBJS := $(TINET_COBJS) \
	               tcp_input.o tcp_output.o tcp_usrreq.o \
	               tcp_subr.o tcp_timer.o tcp_subr_ncs.o
	TINET_CDEFS := $(TINET_CDEFS) -DSUPPORT_TCP

endif

ifeq ($(SUPPORT_UDP),true)

	TINET_COBJS := $(TINET_COBJS) \
	               udp_input.o udp_usrreq.o udp_output.o
	TINET_CDEFS := $(TINET_CDEFS) -DSUPPORT_UDP

endif

#
#  共通コンパイルオプションの定義への追加
#
CDEFS := $(CDEFS) $(TINET_CDEFS)
INCLUDES := $(INCLUDES) -I$(TINET_ROOT)

#
#  アプリケーションプログラムに関する定義への追加
#
TINET_UTASK_CFG = tinet_$(UNAME).cfg

#
#  システムサービスに関する定義への追加
#
STASK_DIR := $(STASK_DIR):$(TINET_DIR)
STASK_COBJS := $(STASK_COBJS) $(TINET_COBJS)
STASK_LIBS := $(STASK_LIBS) -lc

#
#  TINET コンフィギュレーションファイルの生成
#
tinet:
	$(CC) -E $(INCLUDES) $(CDEFS) -x c-header $(TINET_UTASK_CFG) > tmpfile9
	$(TINET_ROOT)/cfg/tinet_cfg -s tmpfile9
	rm -f tmpfile9
